#define WALL_DECON_REINF_NONE 0
#define WALL_DECON_REINF_BULKHEAD_REMOVED 1
#define WALL_DECON_REINF_GRILLE_REMOVED 2
#define WALL_DECON_REINF_BRACING_REMOVED 3
#define WALL_DECON_REINF_BOLTS_UNDONE 4

#define WALL_DECON_NONE 0
#define WALL_DECON_WALL_WEAKENED 1

#define WALL_DECON_STEP_TIME 2 SECONDS
#define WALL_DECON_STEP_REINF_TIME 5 SECONDS

#define COMSIG_WALL_MATERIALS_UPDATED "wall_materials_updated"
